services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_erp_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    depends_on:
      - db
      - mailhog

  web:
    image: nginx:stable-alpine
    container_name: mini_erp_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  db:
    image: mariadb:10.11
    container_name: mini_erp_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog
    container_name: mini_erp_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
  storage_data:
  cache_data:
